Adds completed Q5
kristina-altunina/news pull request #5
Opened 2023-08-16 14:23 UTC by kristina-altunina

2023-08-16 15:09 UTC, Hard-Luck approved these changes
👍 Just a couple of small tweaks then you can merge

2023-08-16 15:09 UTC, Hard-Luck commented on __tests__/api.test.js
> +            expect(article).toHaveProperty('article_id', expect.any(Number));
You know the article id is 1 for this so you dont need to expect any number

2023-08-16 15:09 UTC, Hard-Luck commented on __tests__/api.test.js
> +    it('400: responds with an error message when passed an article_id that is not accepted ', () => {
The description here should say that the article_id is invalid rather than no excepted

2023-08-16 15:09 UTC, Hard-Luck commented on __tests__/api.test.js
> +        expect(article).toHaveProperty('comment_count', expect.any(String));
You could test for the article to not have a body property

2023-08-17 08:01 UTC, Augs0 requested changes
Hey Kristina, well done on implementing the feedback from before. Please be sure to add an expect that looks for the article id of 1 before continuing. Once that is done, you can merge your work

2023-08-17 08:01 UTC, Augs0 commented on __tests__/api.test.js
> -            expect(article).toHaveProperty('article_id', expect.any(Number));
When you were asked to remove the expect any number test by Mark, he meant that you should test specifically for 1 as the article id rather than any number

2023-08-17 08:54 UTC, merged